def update_matplot_rcParams(rcParams: dict):
    rcParams.update(
        {
            "axes.labelpad": 3.0,
            "axes.labelsize": 6.0,
            "axes.titlesize": 6.0,
            "axes.linewidth": 0.5,
            "figure.figsize": [7.5, 5.0],
            "figure.subplot.bottom": 0.0,
            "figure.subplot.hspace": 0.0,
            "figure.subplot.left": 0.0,
            "figure.subplot.right": 1.0,
            "figure.subplot.top": 1.0,
            "figure.subplot.wspace": 0.0,
            "font.size": 6.0,
            "lines.linewidth": 0.5,
            "legend.fontsize": 5.0,
            "legend.labelspacing": 0.1,
            "legend.borderpad": 0.1,
            "legend.handlelength": 1,
            "legend.handletextpad": 0.5,
            "lines.linewidth": 1.0,
            "xtick.labelsize": 5.0,
            "xtick.major.pad": 2.0,
            "xtick.major.size": 2.5,
            "xtick.major.width": 0.5,
            "xtick.minor.pad": 1.4,
            "xtick.minor.size": 1.5,
            "xtick.minor.width": 0.4,
            "ytick.labelsize": 5.0,
            "ytick.major.pad": 2.0,
            "ytick.major.size": 2.5,
            "ytick.major.width": 0.5,
            "ytick.minor.pad": 1.4,
            "ytick.minor.size": 1.5,
            "ytick.minor.width": 0.4,
            "hatch.linewidth": 0.5,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            #'text.usetex': True,
            #'font.family':'serif',
            #'font.serif': 'Palatino',
            #'font.sans-serif':'Helvetica',
            #'font.monospace': 'Courier',
            #'font.family': 'serif',
        }
    )
